// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/finale-surprise/CinematicAtmosphere.tsx": () => import("../components/mockups/finale-surprise/CinematicAtmosphere.tsx"),
  "./components/mockups/finale-surprise/Current.tsx": () => import("../components/mockups/finale-surprise/Current.tsx"),
  "./components/mockups/finale-surprise/WarmGlow.tsx": () => import("../components/mockups/finale-surprise/WarmGlow.tsx")
};
